package org.example.model.user;

public class UserModel {

    private int userId;              // auto-generated by DB
    private String username;
    private String passwordHash;
    private String accessLevel;
    private boolean register;        // whether the user is allowed to register

    // --- Constructors ---

    public UserModel() {
    }

    // Use this when creating a new user (before DB insert)
    public UserModel(String username, String passwordHash, String accessLevel, boolean register) {
        this.username = username;
        this.passwordHash = passwordHash;
        this.accessLevel = accessLevel;
        this.register = register;
    }

    // --- Getters and Setters ---
    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public String getAccessLevel() {
        return accessLevel;
    }

    public void setAccessLevel(String accessLevel) {
        this.accessLevel = accessLevel;
    }

    public boolean isRegister() {
        return register;
    }

    public void setRegister(boolean register) {
        this.register = register;
    }

    @Override
    public String toString() {
        return "UserModel{" +
                "userId=" + userId +
                ", username='" + username + '\'' +
                ", accessLevel='" + accessLevel + '\'' +
                ", register=" + register +
                '}';
    }
}
