package org.example.model.user;

public class UserModel {

    private int userId;              // auto-generated by DB
    private String username;
    private String passwordHash;
    private String accessLevel;
    private boolean register;
    private boolean active;
    private int cartId;

    // --- Constructors ---

    // Use this when creating a new user (before DB insert)
    public UserModel(int userId, String username, String passwordHash, String accessLevel, boolean register,boolean active) {}
    /**
     * Default constructor.
     * Needed for frameworks like Hibernate, JSP/Servlets, or tools that use reflection
     * to create an object without passing parameters.
     */


    /**
     * Full constructor including userId.
     * Use this when retrieving an existing user from the database.
     */

    public UserModel(int userId, String username, String passwordHash, String accessLevel, int cartId) {
        this.userId = userId;
        this.username = username;
        this.passwordHash = passwordHash;
        this.accessLevel = accessLevel;
        this.register = register;
        this.active = active;
        this.cartId = cartId;
    }


        // Use this when loading user from database (with userId)
   public UserModel(String username, String passwordHash, String accessLevel, boolean register, boolean isActive) {
            this.username = username;
            this.passwordHash = passwordHash;
            this.accessLevel = accessLevel;
            this.register = register;
            this.active = isActive;
        }
    public UserModel(String username, String passwordHash, String accessLevel) {
        this.username = username;
        this.passwordHash = passwordHash;
        this.accessLevel = accessLevel;
        this.cartId = 0; // default value indicating no cart assigned yet
    }

    // --- Getters and Setters ---
    public int getUserId() {
        return userId;
    }
    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }

    public String getPasswordHash() {
        return passwordHash;
    }
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public String getAccessLevel() {
        return accessLevel;
    }
    public void setAccessLevel(String accessLevel) {
        this.accessLevel = accessLevel;
    }

    public boolean isRegister() {return this.register;}
    public void setRegister(boolean register) {
        this.register = register;
    }

    public boolean isActive() { return this.active; }
    public void setActive(boolean active) { this.active = active; }

    public int getCartId() {return cartId;}
    public void setCartId(int cartId) {this.cartId = cartId;}

    // --- toString() for easy printing ---
    @Override
    public String toString() {
        return "UserModel{" +
                "userId=" + userId +
                ", username='" + username + '\'' +
                ", accessLevel='" + accessLevel + '\'' +
                ", register=" + register +
                '}';
    }
}
