package org.example.model.user;

public class UserModel {

    private int userId;              // auto-generated by DB
    private String username;
    private String passwordHash;
    private String accessLevel;
    private boolean is_registered;
    private boolean active;

    // --- Constructors ---

    // Use this when creating a new user (before DB insert)
    public UserModel(int userId, String username, String passwordHash, String accessLevel, boolean is_registered,boolean active) {
        this.userId = userId;
        this.username = username;
        this.passwordHash = passwordHash;
        this.accessLevel = accessLevel;
        this.is_registered = is_registered;
        this.active = active;
    }


    // Use this when loading user from database (with userId)
    public UserModel(String username, String passwordHash, String accessLevel, boolean is_registered, boolean isActive) {
        this.username = username;
        this.passwordHash = passwordHash;
        this.accessLevel = accessLevel;
        this.is_registered = is_registered;
        this.active = isActive;
    }

    // --- Getters and Setters ---
    public int getUserId() {
        return userId;
    }
    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }

    public String getPasswordHash() {
        return passwordHash;
    }
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public String getAccessLevel() {
        return accessLevel;
    }
    public void setAccessLevel(String accessLevel) {
        this.accessLevel = accessLevel;
    }

    public boolean isRegister() {return this.is_registered;}
    public void setRegister(boolean is_registered) {
        this.is_registered = is_registered;
    }

    public boolean isActive() { return this.active; }
    public void setActive(boolean active) { this.active = active; }

    @Override
    public String toString() {
        return "UserModel{" +
                "userId=" + userId +
                ", username='" + username + '\'' +
                ", accessLevel='" + accessLevel + '\'' +
                ", is_registered=" + is_registered +
                '}';
    }
}